# Site Settings
title: Mats VdN Curriculum Vitae
url: 'http://bynyden.com'
baseurl: '/online_cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: bn-custom
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-115376140-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
